### ISSUE TITLE
Ne prikazuje preostalo vrijeme do namaza u notifikaciji

### ISSUE THREAD

**Issue by Memis** [vaktija/vaktija.ba-flutter#2]
Nakon zadnjeg ažuriranja više nije moguće podesit da u notifikaciji piše preostalo vrijeme do sljedećeg namaza. Jedina opcija koju imam jeste prikaz dnevne vaktije u notifikaciji.

Uređaj: Samsung s10+ 
Platforma: Android

**Comment by arkaDEV61** [comment]
Ispravljeno u verziji 2.1.1
